# Generated by Django 4.2.2 on 2023-07-09 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publishing_company_id',
            new_name='publishing_company',
        ),
    ]
