# Generated by Django 4.2.2 on 2023-07-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishing_company',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
