# Generated by Django 4.2.2 on 2023-07-10 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_publishing_company_name'),
        ('books', '0002_rename_publishing_company_id_book_publishing_company'),
    ]

    operations = [
    ]
