# Generated by Django 4.2.2 on 2023-07-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='nome',
            field=models.CharField(default=None, max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='permission_loan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=127),
        ),
    ]
