# Generated by Django 4.2.2 on 2023-07-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_address_account_nome_account_permission_loan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='nome',
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
