# Generated by Django 4.2.2 on 2023-07-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_account_nome_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='permission_loan',
            field=models.BooleanField(default=True),
        ),
    ]
