# Generated by Django 4.2.2 on 2023-07-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('books', models.ManyToManyField(related_name='genres', to='books.book')),
            ],
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
