# Generated by Django 4.2.2 on 2023-07-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_gender_delete_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
