# Generated by Django 4.2.2 on 2023-07-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_copy_book', models.IntegerField()),
                ('available', models.BooleanField(default='True')),
                ('conservation_state', models.CharField(max_length=127)),
            ],
        ),
    ]
